### ISSUE TITLE
Rancher service not upgrading

### ISSUE THREAD

**Issue by vishwakhrushi** [jenkinsci/rancher-plugin#19]
I am trying to upgrade a service in the stack in rancher. I am running in to the following issue.
I uninstalled the plugin and manually upgraded to 1.0.9 but still the version shows as 1.0.8-SNAPSHOT. I used the plugin at the link below. 
https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/rancher/1.0.9/rancher-1.0.9.hpi

Deploy/Upgrade image[docker:image-name:tag] to service [stack/service] to rancher environment [http://xxxxxxxxxxxx:8080/v2-beta/projects/xxxx]
Stack already exist. skip
ERROR: Build step failed with exception
java.lang.RuntimeException: Some Error Happen statusCode 404 response: {"id":"60b01c4d-de6f-404b-a338-ffae04b585de","type":"error","links":{},"actions":{},"status":404,"code":"Not Found","message":"Not Found","detail":null,"baseType":"error"}
	at jenkins.plugins.rancher.HttpClient.execute(HttpClient.java:72)
	at jenkins.plugins.rancher.HttpClient.get(HttpClient.java:31)
	at jenkins.plugins.rancher.RancherClient.services(RancherClient.java:39)
	at jenkins.plugins.rancher.RancherBuilder.perform(RancherBuilder.java:94)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Deploy/Upgrade Rancher Service' marked build as failure
Finished: FAILURE

>

**Comment by VenkateshLoganathan** [comment]
I'm also running the same issue. Can anybody post what is the solution to overcome this issue?

**Comment by dicardopegb** [comment]
I'm checking this out, it seems that the services/ API URL is not correct, it's not including the projects/ prefix as it should following the API docs. Will create a PR if that's the case
