### ISSUE TITLE
no upgrade operation was performed

### ISSUE THREAD

**Issue by kys1230** [jenkinsci/rancher-plugin#39]
Upgrade the specified service by calling the rancher API through the Jenkins pipeline, result is error message:
```text
Deploy/Upgrade image[docker:<image_url>:<image_tagid>] to service [<stack_name>/<server_name>] to rancher environment [http://<rancher_api_host>:<rancher_api_port>/v2-beta/projects/<project_id>]
Stack already exist. skip
Upgrading service instance
service <server_name> current state is active
```
In fact, no upgrade operation was performed.

**Comment by EslamElHusseiny** [comment]
Same issue happened to me with the following error
```
java.lang.NullPointerException
	at jenkins.plugins.rancher.RancherBuilder.upgradeService(RancherBuilder.java:157)
	at jenkins.plugins.rancher.RancherBuilder.perform(RancherBuilder.java:107)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
