### ISSUE TITLE
Doesn't work with Jenkins 2.387.1

### ISSUE THREAD

**Issue by mjaggard** [jenkinsci/rancher-plugin#55]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.387.1
OS: Linux - 4.4.0-1128-aws
Java: 11.0.18 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
adoptopenjdk:1.5
ansicolor:1.0.2
ant:481.v7b_09e538fcca
antisamy-markup-formatter:159.v25b_c67cd35fb_
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
authentication-tokens:1.4
aws-credentials:191.vcb_f183ce58b_9
aws-java-sdk:1.12.406-374.v4cdf53953691
aws-java-sdk-cloudformation:1.12.406-374.v4cdf53953691
aws-java-sdk-codebuild:1.12.406-374.v4cdf53953691
aws-java-sdk-ec2:1.12.406-374.v4cdf53953691
aws-java-sdk-ecr:1.12.406-374.v4cdf53953691
aws-java-sdk-ecs:1.12.406-374.v4cdf53953691
aws-java-sdk-efs:1.12.406-374.v4cdf53953691
aws-java-sdk-elasticbeanstalk:1.12.406-374.v4cdf53953691
aws-java-sdk-iam:1.12.406-374.v4cdf53953691
aws-java-sdk-logs:1.12.406-374.v4cdf53953691
aws-java-sdk-minimal:1.12.406-374.v4cdf53953691
aws-java-sdk-sns:1.12.406-374.v4cdf53953691
aws-java-sdk-sqs:1.12.406-374.v4cdf53953691
aws-java-sdk-ssm:1.12.406-374.v4cdf53953691
basic-branch-build-strategies:71.vc1421f89888e
blueocean:1.27.3
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.3
blueocean-commons:1.27.3
blueocean-config:1.27.3
blueocean-core-js:1.27.3
blueocean-dashboard:1.27.3
blueocean-display-url:2.4.1
blueocean-events:1.27.3
blueocean-git-pipeline:1.27.3
blueocean-github-pipeline:1.27.3
blueocean-i18n:1.27.3
blueocean-jira:1.27.3
blueocean-jwt:1.27.3
blueocean-personalization:1.27.3
blueocean-pipeline-api-impl:1.27.3
blueocean-pipeline-editor:1.27.3
blueocean-pipeline-scm-api:1.27.3
blueocean-rest:1.27.3
blueocean-rest-impl:1.27.3
blueocean-web:1.27.3
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.2-2
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-failure-analyzer:2.4.1
build-time-blame:64.vd8f4018a2bbe
build-timeout:1.28
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:2.0.0
cloudbees-bitbucket-branch-source:800.va_b_b_9a_a_5035c1
cloudbees-folder:6.815.v0dd5a_cb_40e0e
codebuilder-cloud:1.0.1
command-launcher:90.v669d7ccb_7c31
commons-httpclient3-api:3.1-3
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
config-file-provider:3.11.1
credentials:1224.vc23ca_a_9a_2cb_0
credentials-binding:523.vd859a_4b_122e6
cucumber-perf:2.0.9
data-tables-api:1.13.3-3
database:191.vd5981b_97a_5fa_
database-mysql:1.4
display-url-api:2.3.7
docker-commons:419.v8e3cd84ef49c
docker-workflow:563.vd5d2e5c4007f
durable-task:504.vb10d1ae5ba2f
ec2:2.0.6
ec2-fleet:2.5.2
echarts-api:5.4.0-3
email-ext:2.95
favorite:2.4.1
font-awesome-api:6.3.0-2
git:5.0.0
git-client:4.2.0
git-parameter:0.9.18
git-server:99.va_0826a_b_cdfa_d
github:1.37.0
github-api:1.303-417.ve35d9dd78549
github-branch-source:1703.vd5a_2b_29c6cdc
github-oauth:0.39
google-login:1.7
gradle:2.3.2
h2-api:1.4.199
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.31
http_request:1.16
instance-identity:142.v04572ca_5b_265
ionicons-api:45.vf54fca_5d2154
jackson2-api:2.14.2-319.v37853346a_229
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jenkins-design-language:1.27.3
jersey2-api:2.39.1-1
jira:3.9
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.16-2
jquery:1.12.4-1
jquery3-api:3.6.4-1
jsch:0.1.55.61.va_e9ee26616e7
junit:1189.v1b_e593637fa_e
junit-realtime-test-reporter:102.v3f020960a_646
ldap:671.v2a_9192a_7419d
lockable-resources:1131.vb_7c3d377e723
mailer:448.v5b_97805e3767
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.1.6
matrix-project:785.v06b_7f47b_c631
mercurial:1260.vdfb_723cdcc81
metrics:4.2.13-420.vea_2f17932dd6
mina-sshd-api-common:2.9.2-62.v199162f0a_2f8
mina-sshd-api-core:2.9.2-62.v199162f0a_2f8
node-iterator-api:49.v58a_8b_35f8363
nodejs:1.6.0
okhttp-api:4.10.0-132.v7a_7b_91cef39c
openJDK-native-plugin:1.6
pam-auth:1.10
pipeline-build-step:487.va_823138eee8b_
pipeline-github:2.8-138.d766e30bb08b
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-maven:1279.v5d711113020f
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2125.vddb_a_44a_d605e
pipeline-model-definition:2.2125.vddb_a_44a_d605e
pipeline-model-extensions:2.2125.vddb_a_44a_d605e
pipeline-npm:49.v9c8598493533
pipeline-rest-api:2.32
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2125.vddb_a_44a_d605e
pipeline-stage-view:2.32
pipeline-utility-steps:2.15.1
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.2.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
pubsub-light:1.17
rancher:1.0.13-SNAPSHOT (private-12/31/2018 16:31-yunlong)
resource-disposer:0.21
scm-api:631.v9143df5b_e4a_a
script-security:1229.v4880b_b_e905a_6
simple-theme-plugin:146.v0e67db_a_9052e
slack:631.v40deea_40323b
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
sonar:2.15
sse-gateway:1.26
ssh-credentials:305.v8f4381501156
ssh-slaves:2.877.v365f5eb_a_b_eec
sshd:3.275.v9e17c10f2571
structs:324.va_f5d6774f3a_d
timestamper:1.23
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
workflow-aggregator:596.v8c21c963d92d
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:1010.vf7a_b_98e847c1
workflow-cps:3653.v07ea_433c90b_4
workflow-durable-task-step:1241.v1a_63e465f943
workflow-job:1289.vd1c337fd5354
workflow-multibranch:733.v109046189126
workflow-scm-step:408.v7d5b_135a_b_d49
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.44
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. Run a rancher deployment
2. See the error `java.lang.ClassNotFoundException: org.apache.commons.httpclient.HttpMethod`

### Expected Results

The deployment runs

### Actual Results

```
java.lang.ClassNotFoundException: org.apache.commons.httpclient.HttpMethod
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at hudson.util.MaskingClassLoader.loadClass(MaskingClassLoader.java:80)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at hudson.PluginFirstClassLoader2.loadClass(PluginFirstClassLoader2.java:69)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Also:   java.lang.ClassNotFoundException: org.apache.commons.httpclient.HttpMethod
		at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
		at hudson.util.MaskingClassLoader.loadClass(MaskingClassLoader.java:80)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
		at hudson.PluginFirstClassLoader2.loadClass(PluginFirstClassLoader2.java:69)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	Caused: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpMethod
Caused: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpMethod
	at jenkins.plugins.rancher.RancherBuilder.newRancherClient(RancherBuilder.java:138)
	at jenkins.plugins.rancher.RancherBuilder.initializeClient(RancherBuilder.java:130)
	at jenkins.plugins.rancher.RancherBuilder.perform(RancherBuilder.java:91)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
```

**Comment by sd8089730** [comment]
Have you solved it？ @mjaggard

**Comment by mjaggard** [comment]
No. I got as far as looking at the plugin code but didn't work out what needs changing to make this work.

**Comment by sd8089730** [comment]
@mjaggard try this https://github.com/sd8089730/rancher-plugin/releases/tag/v2.0.1
