### ISSUE TITLE
Can not update docker container

### ISSUE THREAD

**Issue by dlednik** [jenkinsci/rancher-plugin#8]
```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at jenkins.plugins.rancher.RancherBuilder.getStack(RancherBuilder.java:192)
	at jenkins.plugins.rancher.RancherBuilder.perform(RancherBuilder.java:79)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
```

**Comment by dlednik** [comment]
found out the correct parameters, my bad
